// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrRabL8Gs7BPN0ArTbJVuzQc08XrTM_8k',
    appId: '1:227294988622:web:8e0a36a1bfb7ecf696f61f',
    messagingSenderId: '227294988622',
    projectId: 'fiire-base-otp',
    authDomain: 'fiire-base-otp.firebaseapp.com',
    storageBucket: 'fiire-base-otp.firebasestorage.app',
    measurementId: 'G-492NCV8F63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXiggvutVUapanVI8dzFcHe-8wEWsz6eY',
    appId: '1:227294988622:android:67bcb6215fa5605896f61f',
    messagingSenderId: '227294988622',
    projectId: 'fiire-base-otp',
    storageBucket: 'fiire-base-otp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrRabL8Gs7BPN0ArTbJVuzQc08XrTM_8k',
    appId: '1:227294988622:web:345a7fe4d2217a1296f61f',
    messagingSenderId: '227294988622',
    projectId: 'fiire-base-otp',
    authDomain: 'fiire-base-otp.firebaseapp.com',
    storageBucket: 'fiire-base-otp.firebasestorage.app',
    measurementId: 'G-KRR2XL7X8C',
  );

}